Traceback (most recent call last):
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/rodolpho/Projects/bayesian/BAYES/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# ===============================================
#    Plot da Posteriori da B-Spline de Grau 3
# ===============================================
plt.figure(figsize=(17, 9))

plt.scatter(cherry_not_na.year, cherry_not_na.temp, marker='o', alpha=0.5, s=7)  # Plot da amostra

plt.fill_between(cherry_not_na.year, HPDI_posteriori_spline_3[:, 0], HPDI_posteriori_spline_3[:, 1],  # Plot HPDI
         color='red', alpha=0.3, label='HPDI da Posteriori') 

plt.plot(cherry_not_na.year, mean_posteriori_spline_3, color='black', label='M√©dia da posteriori')  # Plot da M√©dia

plt.plot(cherry_not_na.year, alpha_spline_3[:, :n_plot] + Bw_spline_3[:, :n_plot],  # Plot do Intevalo da M√©dia (Sem o HPDI)
         color='red', linewidth=0.1, alpha=0.1) 

plt.title('Posteriori da B-Spline \n HPDI de ' + str(intervalo_credibilidade) + '%')
plt.xlabel('Ano')
plt.ylabel('Posteriori \n (Temperatura de Mar√ßo)')
plt.grid(ls='--', color='white', alpha=0.6)

plt.text(2000, 8.1, 'Um problema que pode acontecer \n quando geramos a spline com a \n √∫ltima e a primeira ponta da fun√ß√£o \n "presa".')

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_81404/1197164469.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mcherry_not_na[0m[0;34m.[0m[0myear[0m[0;34m,[0m [0mmean_posteriori_spline_3[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m'black'[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'M√©dia da posteriori'[0m[0;34m)[0m  [0;31m# Plot da M√©dia[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;34m[0m[0m
[0;32m---> 13[0;31m plt.plot(cherry_not_na.year, alpha_spline_3[:, :n_plot] + Bw_spline_3[:, :n_plot],  # Plot do Intevalo da M√©dia (Sem o HPDI)
[0m[1;32m     14[0m          color='red', linewidth=0.1, alpha=0.1) 
[1;32m     15[0m [0;34m[0m[0m

[0;31mIndexError[0m: too many indices for array: array is 1-dimensional, but 2 were indexed
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

